### ISSUE TITLE
[Suggestion] Can you add something like jump cutter in it ?

### ISSUE THREAD

**Issue by chamanbabangogo** [FilippVolodin/ReeePlayer#1]
https://github.com/WofWca/jumpcutter

Can you embed something like in this app?? it would be win win!

**Comment by FilippVolodin** [comment]
Great idea, thank you! I'll think about it.

**Comment by FilippVolodin** [comment]
@chamanbabangogo done. Version 0.3 has Voice Activity Detection support for skip, fast forward and volume down non-voice parts in real time.
