### ISSUE TITLE
Режим повторения, проблема с замедлением скорости воспроизведения

### ISSUE THREAD

**Issue by IvanFXG** [FilippVolodin/ReeePlayer#2]
После обновления приложения в режиме повторения (Repeat Clips) скорость воспроизведения не меняется на классическое 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, а доступны лишь новые скорости - 0.5, 0.75, 1, 1.25, 1.5, 2, при этом 0.75 не всегда воспроизводиться. 
В предыдущей версии были доступны медленные скорости воспроизведения, из моего опыта наиболее полезны 0.8, 0.9,  Эти скорости всегда корректно воспроизводятся и наиболее подходят для изучающих и вслушивающихся в незнакомую речь. 
Пожалуйста, верните их, или же добавьте возможность переключения между двумя скоростными режимами - старым, в котором доступно было только замедление, и новым, в котором разброс скоростей больше.

**Comment by FilippVolodin** [comment]
@IvanFXG ок, согласен. В качестве временного решения можете заменить ReeePlayer.exe на [этот](https://github.com/FilippVolodin/ReeePlayer/files/7917763/ReeePlayer.zip) - новая версия со старыми скоростями. Пока я не очень уверен как сделать лучше, чтобы покрыть широкий диапазон скоростей и обеспечить их быстрый выбор и мышкой и клавишами. Или быть дать возможность пользователю самостоятельно выбрать желаемые скорости и хоткеи для них. Если есть идеи, то можете поделиться.
Сейчас я добавляю движок Chromium для воспроизведения, поэтому изменение скорости будет происходить гораздо плавнее и быстрее.

**Comment by FilippVolodin** [comment]
@IvanFXG в версии 0.3 теперь такие скорости: 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.25, 1.5, 2. Еще теперь можно использовать движок Chromium для просмотра, он, как я говорил, адекватнее меняет скорость.
